image_sizes:
  cover: 1024
  thumbnail: 450
  full: 3840
jpg_quality: 85
output_path: "./export"
source_path: "./galleries"
galleries_per_page: 12
images_per_gallery_page: 20
exif_fields:
  - DateTimeOriginal
  - LensModel
  - FocalLength
  - ExposureTime
  - FNumber
  - ISO
site_name: "My Photography Gallery"
author: "My Name"