site_name: "My Photography Gallery"
output_path: "./export"
source_path: "./galleries"
author: "My Name"
image_sizes:
  cover: 1024
  thumbnail: 450
  full: 3840
jpg_quality: 85
exif_fields:
  - DateTimeOriginal
  - LensModel
  - FocalLength
  - ExposureTime
  - FNumber
  - ISO
aws:
  access_key_id: YOUR_ACCESS_KEY_ID
  secret_access_key: YOUR_SECRET_ACCESS_KEY
  region: YOUR_REGION
  bucket_name: YOUR_BUCKET_NAME