site_name: "My Photography Gallery"
output_path: "./export"
source_path: "./galleries"
author: "My Name"
image_sizes:
  cover: 1024
  thumbnail: 450
  full: 3840
jpg_quality: 85
exif_fields:
  - DateTimeOriginal
  - LensModel
  - FocalLength
  - ExposureTime
  - FNumber
  - ISO
aws:
  access_key_id: XXX
  secret_access_key: XXX
  region: us-west-1
  s3:
    bucket_name: XXX
  cloudfront:
    distribution_id: XXX
    default_root_object: index.html